sudo: required
dist: trusty
language: cpp
compiler:
 - gcc

env:
 - RUN_OPENGL_TESTS=false
 - RUN_OPENGL_TESTS=true

matrix:
 allow_failures:
 - env: RUN_OPENGL_TESTS=true

before_install:
# Get Qt dev packages
 - export QT_VERSION=56
 - sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty
 - sudo apt-get update -q
 - sudo apt-get -y install qt${QT_VERSION}declarative
 - sudo apt-get -y install qt${QT_VERSION}quickcontrols
 - sudo apt-get -y install qt${QT_VERSION}tools 
# set up xvfb
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
 - source /opt/qt${QT_VERSION}/bin/qt${QT_VERSION}-env.sh
 - mkdir build
 - cd build
 - qmake mosaic_all.pro -r QMAKE_CC=$CC QMAKE_CXX=$CXX ../
 - make -j2
 - make check
