sudo: required
dist: trusy
language: cpp
compiler:
 - gcc

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -q
 - sudo apt-get install qtbase5-dev
 - #sudo apt-get install qt5-default
 - sudo apt-get install qtdeclarative5-dev
 - sudo apt-get install libqt5webkit5-dev 
 - sudo apt-get install qttools5-dev-tools

script:
 - source /opt/qt${QT_VERSION}/bin/qt${QT_VERSION}-env.sh
 - qmake mosaic_all.pro -r QMAKE_CC=$CC QMAKE_CXX=$CXX
 - make -j2
 - make check
